// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOlTA9RYYoydP_km_i68UU5WUk2q7dRV0',
    appId: '1:31698346779:web:c46a21beca9d5388f269be',
    messagingSenderId: '31698346779',
    projectId: 'bootsup-3d44d',
    authDomain: 'bootsup-3d44d.firebaseapp.com',
    storageBucket: 'bootsup-3d44d.appspot.com',
    measurementId: 'G-X2R50G67HD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9o53w6zKq8PhNE-rRf8ZhxRvjRc8v5KE',
    appId: '1:31698346779:android:c0c382355d52db9df269be',
    messagingSenderId: '31698346779',
    projectId: 'bootsup-3d44d',
    storageBucket: 'bootsup-3d44d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD38uS8jMVdLVmhKWZ58RvnN8IJOVYcahk',
    appId: '1:31698346779:ios:6d092ce172fdeb79f269be',
    messagingSenderId: '31698346779',
    projectId: 'bootsup-3d44d',
    storageBucket: 'bootsup-3d44d.appspot.com',
    iosBundleId: 'com.example.bootsup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD38uS8jMVdLVmhKWZ58RvnN8IJOVYcahk',
    appId: '1:31698346779:ios:6d092ce172fdeb79f269be',
    messagingSenderId: '31698346779',
    projectId: 'bootsup-3d44d',
    storageBucket: 'bootsup-3d44d.appspot.com',
    iosBundleId: 'com.example.bootsup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOlTA9RYYoydP_km_i68UU5WUk2q7dRV0',
    appId: '1:31698346779:web:9e29061db41680f9f269be',
    messagingSenderId: '31698346779',
    projectId: 'bootsup-3d44d',
    authDomain: 'bootsup-3d44d.firebaseapp.com',
    storageBucket: 'bootsup-3d44d.appspot.com',
    measurementId: 'G-D7YWTLZBD4',
  );
}
